import { useEffect, useRef } from "react";
import { useForm } from "react-hook-form";
import {
  ArrowLeft,
  CheckCircle2,
  Loader2,
  Send,
  Users,
  Wand2,
} from "lucide-react";
import { useNavigation } from "../store/navigation";
import { useOutreachStore } from "../store/outreach";
import { useOutreach } from "../hooks/useOutreach";
import ChannelPicker from "../components/ChannelPicker";
import MessagePreview from "../components/MessagePreview";
import EmptyState from "../components/EmptyState";
import { ApiError } from "../services/client";
import type { OutreachChannel } from "../types/api";

const DEFAULT_TEMPLATE = `Olá {name}! Tudo bem?

Sou do time da scrapAI e encontrei o segmento {segment} da sua empresa em {city}. Acredito que podemos construir uma parceria interessante e gostaria de conversar sobre uma oportunidade.

Podemos agendar uma conversa rápida?`;

interface TemplateFormValues {
  template: string;
}

export default function OutreachPage() {
  const jobId = useNavigation((state) => state.jobId);
  const navigate = useNavigation((state) => state.navigate);

  const leadIds = useOutreachStore((state) => state.leadIds);
  const channel = useOutreachStore((state) => state.channel);
  const setChannel = useOutreachStore((state) => state.setChannel);

  const { choose, send, preview, setPreview } = useOutreach();

  const { register, getValues, handleSubmit } = useForm<TemplateFormValues>({
    defaultValues: { template: DEFAULT_TEMPLATE },
  });

  const generate = () => {
    if (!jobId || leadIds.length === 0) return;
    choose.mutate({
      job_id: jobId,
      channel,
      lead_ids: leadIds,
      template: getValues("template"),
    });
  };

  const generateRef = useRef(generate);
  generateRef.current = generate;

  const autoGenerated = useRef(false);
  useEffect(() => {
    if (!autoGenerated.current) {
      autoGenerated.current = true;
      generateRef.current();
    }
  }, []);

  const handleChannelChange = (next: OutreachChannel) => {
    if (next !== channel) {
      setChannel(next);
      setPreview(null);
    }
  };

  const errorMessage =
    choose.error instanceof ApiError ? choose.error.detail : choose.error?.message ?? null;

  const sendErrorMessage =
    send.error instanceof ApiError ? send.error.detail : send.error?.message ?? null;

  if (!jobId) {
    return (
      <EmptyState
        icon={Users}
        title="Nenhum job selecionado"
        message="Inicie uma busca e selecione leads para enviar mensagens."
        actionLabel="Nova busca"
        onAction={() => navigate("new")}
      />
    );
  }

  if (leadIds.length === 0) {
    return (
      <EmptyState
        icon={Users}
        title="Nenhum lead selecionado"
        message="Selecione leads na página de resultados para preparar o envio."
        actionLabel="Ver resultados"
        onAction={() => navigate("leads")}
      />
    );
  }

  return (
    <div className="mx-auto max-w-4xl">
      <div className="mb-8 flex flex-wrap items-center justify-between gap-4">
        <div>
          <h1 className="text-3xl font-black">Outreach</h1>
          <p className="mt-1 text-slate-400">
            {leadIds.length} lead(s) selecionado(s) · canal:{" "}
            {channel === "email" ? "E-mail" : "WhatsApp"}
          </p>
        </div>

        <button
          type="button"
          onClick={() => navigate("leads")}
          className="inline-flex items-center gap-2 text-sm font-semibold text-slate-400 transition hover:text-cyan-300"
        >
          <ArrowLeft className="h-4 w-4" />
          Voltar aos resultados
        </button>
      </div>

      <div className="space-y-6">
        <div className="rounded-2xl border border-slate-800 bg-slate-900 p-6">
          <h2 className="mb-4 text-sm font-semibold uppercase tracking-wider text-slate-400">
            Canal de envio
          </h2>
          <ChannelPicker value={channel} onChange={handleChannelChange} />
        </div>

        <form
          onSubmit={handleSubmit(generate)}
          className="rounded-2xl border border-slate-800 bg-slate-900 p-6"
        >
          <h2 className="mb-1 text-sm font-semibold uppercase tracking-wider text-slate-400">
            Template da mensagem
          </h2>
          <p className="mb-4 text-xs text-slate-500">
            Use os marcadores {"{name}"}, {"{segment}"} e {"{city}"} para personalizar cada
            mensagem.
          </p>

          <textarea
            rows={8}
            {...register("template")}
            className="w-full resize-y rounded-xl border border-slate-700 bg-slate-950 p-4 font-mono text-sm text-slate-100 outline-none transition focus:border-cyan-400"
          />

          {errorMessage && (
            <div className="mt-4 rounded-xl border border-rose-500/30 bg-rose-500/10 p-4 text-sm text-rose-300">
              {errorMessage}
            </div>
          )}

          <button
            type="submit"
            disabled={choose.isPending}
            className="mt-4 inline-flex items-center gap-2 rounded-xl bg-cyan-500 px-6 py-3 font-semibold text-slate-950 transition hover:bg-cyan-400 disabled:cursor-not-allowed disabled:opacity-50"
          >
            {choose.isPending ? (
              <Loader2 className="h-5 w-5 animate-spin" />
            ) : (
              <Wand2 className="h-5 w-5" />
            )}
            {preview ? "Atualizar prévia" : "Gerar prévia"}
          </button>
        </form>

        {choose.isPending && (
          <div className="flex items-center gap-3 rounded-2xl border border-slate-800 bg-slate-900 p-6 text-slate-400">
            <Loader2 className="h-5 w-5 animate-spin text-cyan-400" />
            Gerando mensagens personalizadas...
          </div>
        )}

        {preview && (
          <>
            <MessagePreview channel={preview.channel} recipients={preview.recipients} />

            {send.isSuccess ? (
              <div className="rounded-2xl border border-emerald-500/30 bg-emerald-500/10 p-6">
                <p className="flex items-center gap-2 font-bold text-emerald-300">
                  <CheckCircle2 className="h-5 w-5" />
                  Mensagens enviadas com sucesso!
                </p>
                <p className="mt-2 text-sm text-emerald-200/80">
                  {send.data.delivered} mensagem(ns) entregue(s) para {preview.recipients.length}{" "}
                  destinatário(s).
                </p>
                {send.data.stub && (
                  <p className="mt-2 text-sm text-emerald-200/60">
                    {send.data.message} — Envio real desativado nesta versão.
                  </p>
                )}
              </div>
            ) : (
              <button
                type="button"
                onClick={() => send.mutate({ plan_id: preview.id })}
                disabled={send.isPending}
                className="flex w-full items-center justify-center gap-2 rounded-xl bg-emerald-500 px-8 py-4 font-bold text-slate-950 transition hover:bg-emerald-400 disabled:cursor-not-allowed disabled:opacity-50"
              >
                {send.isPending ? (
                  <Loader2 className="h-5 w-5 animate-spin" />
                ) : (
                  <Send className="h-5 w-5" />
                )}
                Enviar mensagens
              </button>
            )}

            {sendErrorMessage && (
              <div className="rounded-xl border border-rose-500/30 bg-rose-500/10 p-4 text-sm text-rose-300">
                {sendErrorMessage}
              </div>
            )}
          </>
        )}
      </div>
    </div>
  );
}
